dataset: llff
batching: all_images
num_coarse_samples: 64
num_fine_samples: 128
use_viewdirs: true
white_bkgd: false
batch_size: 4096
randomized: true
near: 0.1
far: 3
factor: 0
llffhold: 8
noise_std: 1.
lr_init: 2.0e-3
lr_final: 2.0e-5
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 250000
save_every: 2500
render_every: 1200
print_every: 100
gc_every: 5000
spherify: true
lindisp: true
use_pixel_centers: true
