dataset: llff
num_train_cameras: 50
num_coarse_samples: 32
white_bkgd: true
batch_size: 1024
near: 0.2
far: 20
factor: 0
llffhold: 8
noise_std: 1.
lr_init: 2.0e-3
lr_final: 2.0e-5
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 250000
save_every: 2500
render_every: 1200
print_every: 100
gc_every: 0
train_matplotlib: false
eval_on_train: true
tags: force_same_image_size
