dataset: llff
batching: all_images
num_coarse_samples: 32
num_fine_samples: 128
use_viewdirs: true
white_bkgd: false
randomized: true
near: 0.1
far: 10.
factor: 8
llffhold: 8
noise_std: 1.
spherify: True
lindisp: True
use_pixel_centers: true
gc_every: 2000
max_steps: 150000
lr_init: 2.0e-3
lr_final: 2.0e-5
lr_delay_steps: 2500
lr_delay_mult: 0.1
save_every: 2500
render_every: 1200
print_every: 100
batch_size: 2048
