py_library(
    name = "plot3d_plotly",
    srcs = [
        "plot3d_plotly.py",
    ],
    deps = [
        "//third_party/py/numpy",
        "//third_party/py/plotly:plotly_colab",
        "//third_party/py/plotly/express",
        "//third_party/py/plotly/graph_objects",
    ],
)
