dataset: shapenetseg
num_coarse_samples: 32
white_bkgd: true
batch_size: 1024
near: 0.2
far: 5
factor: 0
noise_std: 1.
lr_init: 2.0e-3
lr_final: 2.0e-5
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 250000
save_every: 2500
render_every: 1200
print_every: 100
gc_every: 0
# TODO(daeyun): This should be renamed. Includes both train and test.
num_train_cameras: 24
train_matplotlib: false
llffhold: 0
example_indices_train: 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23
# Three seen followed by three unseen.
example_indices_eval: 1, 5, 13, 0, 8, 16
